### ISSUE TITLE
1. Introduction - prepare isuues

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#109]
# Part 1 Introduction

- [x] About the course, information versus data, algorithm versus program, type - what does it mean
- [x]  Useful assets: C# language, Visual Studio, GitHub
- [x]  Program robustness: exception, unit tests, environment simulation

## Scope
- [x] create derived tasks 
- [x] close this issue

Milestone:
https://github.com/mpostol/TP/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.+Introduction%22

**Comment by mpostol** [comment]
Done.
