### ISSUE TITLE
 Part 1. Introduction About the course

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#113]
# Part 1. Introduction - prepare issues #109

 About the course, information versus data, algorithm versus program, type - what does it mean

## Scope

- [x] review existing code
- [x] add a placeholder to the project
- [x] add code example  - consider merging with type compatibility
- [x] [Roman numerals to integers](https://stackoverflow.com/questions/14900228/roman-numerals-to-integers)
- [x] add unit tests

**Comment by mpostol** [comment]
Refered in: ad6fe7004bf776204028883a45e48ed36a325890
