### ISSUE TITLE
Part 1. Introduction Useful assets: C# language, Visual Studio, GitHub

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#114]
# Part 1. Introduction - prepare isuues #109

## Scope

- [x] review existing code
- [x] add a placeholder to the project
- [x] add code example  - consider merging with type compatibility
- [x] add unit tests
- [x] text enhancements
