### ISSUE TITLE
Part 1. Introduction: Program robustness: exception, unit tests, environment simulation

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#115]
# Part 1. Introduction - prepare isuues #109

> 3. Program robustness: exception, unit tests, environment simulation

## Scope

- [ ] review existing code
- [ ] add a placeholder to the project
- [ ] add code example  - consider merging with type compatibility
- [ ] add unit tests

**Comment by mpostol** [comment]
The topic is deprecated.
