### ISSUE TITLE
ExDM External Data Management PR to master and delete the branch

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#396]
## Tasks
- [x] PR to master
- [x] Review the associated issues
- [x] Update the doc folder
- [x] Update the ebook
- [x] Make release
